### ISSUE TITLE
Code release

### ISSUE THREAD

**Issue by csEylLee** [CAMMA-public/rendezvous-in-time#1]
Hi, when will the code be open access?

**Comment by csEylLee** [comment]
hello?

**Comment by srv902** [comment]
Hi, 

Thanks for your interest in our work.

The code will be released soon after the IPCAI conference before the end of June.

**Comment by csEylLee** [comment]
> Hi,
> 
> Thanks for your interest in our work.
> 
> The code will be released soon after the IPCAI conference before the end of June.

Emmmm, could the code be released now?

**Comment by cascat0** [comment]
> Hi,
> 
> Thanks for your interest in our work.
> 
> The code will be released soon after the IPCAI conference before the end of June.

When can the code be open source?

**Comment by srv902** [comment]
Hi,

The code to train RiT is released.
